server:
  port: 8600
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800

# FastDFS
fdfs:
  # socket读取超时时间
  so-timeout: 20000
  # 获取连接超时时间
  connect-timeout: 1000
  # tracker列表
  tracker-list:
    - 192.168.0.12:22122
    - 192.168.0.13:22122
  pool:
    max-total: 512
    max-wait-millis: 150